import type { Entity } from "@/lib/catalog-types";

export const entities: Entity[] = [
  { id: "openhands", type: "agent", slug: "openhands", name: "OpenHands", developer: "OpenHands", summary: "Open-source software-agent project; this site verifies repository identity separately from editorial capability summaries.", summaryKind: "editorial", sourceUrl: "https://github.com/OpenHands/OpenHands", sourceLabel: "Official upstream repository", categories: ["coding", "software-engineering"], verification: "verified", evidenceIds: ["ev-openhands"] },
  { id: "cline", type: "agent", slug: "cline", name: "Cline", developer: "Cline", summary: "Open-source coding-agent project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/cline/cline", sourceLabel: "Official upstream repository", categories: ["coding", "ide"], verification: "verified", evidenceIds: ["ev-cline"] },
  { id: "aider", type: "agent", slug: "aider", name: "Aider", developer: "Aider AI", summary: "Open-source terminal coding project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/Aider-AI/aider", sourceLabel: "Official upstream repository", categories: ["coding", "cli"], verification: "verified", evidenceIds: ["ev-aider"] },
  { id: "gemini-cli", type: "agent", slug: "gemini-cli", name: "Gemini CLI", developer: "Google", summary: "Google-maintained terminal agent project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/google-gemini/gemini-cli", sourceLabel: "Official upstream repository", categories: ["coding", "cli"], verification: "verified", evidenceIds: ["ev-gemini-cli"] },
  { id: "qwen-code", type: "agent", slug: "qwen-code", name: "Qwen Code", developer: "Qwen", summary: "Qwen-maintained coding-agent project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/QwenLM/qwen-code", sourceLabel: "Official upstream repository", categories: ["coding", "cli"], verification: "verified", evidenceIds: ["ev-qwen-code"] },
  { id: "swe-agent", type: "agent", slug: "swe-agent", name: "SWE-agent", developer: "SWE-agent", summary: "Software-engineering agent research project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/SWE-agent/SWE-agent", sourceLabel: "Official upstream repository", categories: ["coding", "research"], verification: "verified", evidenceIds: ["ev-swe-agent"] },
  { id: "browser-use", type: "agent", slug: "browser-use", name: "Browser Use", developer: "Browser Use", summary: "Browser-agent project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/browser-use/browser-use", sourceLabel: "Official upstream repository", categories: ["browser", "automation"], verification: "verified", evidenceIds: ["ev-browser-use"] },
  { id: "gpt-researcher", type: "agent", slug: "gpt-researcher", name: "GPT Researcher", developer: "GPT Researcher", summary: "Open-source research-agent project with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/assafelovic/gpt-researcher", sourceLabel: "Official upstream repository", categories: ["research"], verification: "verified", evidenceIds: ["ev-gpt-researcher"] },
  { id: "langgraph", type: "framework", slug: "langgraph", name: "LangGraph", developer: "LangChain", summary: "Stateful agent-workflow framework with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/langchain-ai/langgraph", sourceLabel: "Official upstream repository", categories: ["orchestration", "framework"], verification: "verified", evidenceIds: ["ev-langgraph"] },
  { id: "langchain", type: "framework", slug: "langchain", name: "LangChain", developer: "LangChain", summary: "Open-source application and agent framework with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/langchain-ai/langchain", sourceLabel: "Official upstream repository", categories: ["framework", "orchestration"], verification: "verified", evidenceIds: ["ev-langchain"] },
  { id: "microsoft-agent-framework", type: "framework", slug: "microsoft-agent-framework", name: "Microsoft Agent Framework", developer: "Microsoft", summary: "Microsoft-maintained agent framework with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/microsoft/agent-framework", sourceLabel: "Official upstream repository", categories: ["framework", "orchestration"], verification: "verified", evidenceIds: ["ev-microsoft-agent-framework"] },
  { id: "autogen", type: "framework", slug: "autogen", name: "AutoGen", developer: "Microsoft", summary: "Microsoft agent framework retained as a distinct entity; current lifecycle guidance should be read from its upstream source.", summaryKind: "editorial", sourceUrl: "https://github.com/microsoft/autogen", sourceLabel: "Official upstream repository", categories: ["framework", "multi-agent"], verification: "verified", evidenceIds: ["ev-autogen"] },
  { id: "crewai", type: "framework", slug: "crewai", name: "CrewAI", developer: "CrewAI", summary: "Open-source multi-agent orchestration framework with a public upstream repository.", summaryKind: "editorial", sourceUrl: "https://github.com/crewAIInc/crewAI", sourceLabel: "Official upstream repository", categories: ["framework", "multi-agent"], verification: "verified", evidenceIds: ["ev-crewai"] },
  { id: "sarvam-30b", type: "model", slug: "sarvam-30b", name: "Sarvam-30B", developer: "Sarvam AI", summary: "A Mixture-of-Experts text-generation model with a strong India-language focus. Model-card-reported benchmark results are not promoted as independent rankings.", summaryKind: "source-derived", sourceUrl: "https://huggingface.co/sarvamai/sarvam-30b", sourceLabel: "Official model card", categories: ["model", "indic", "local"], indiaRelevance: "Indian / Indic model ecosystem", local: true, verification: "verified", evidenceIds: ["ev-sarvam-30b"], facts: {"activeParameters":"2.4B non-embedding","architecture":"Mixture-of-Experts","developer":"Sarvam AI","indiaFocus":true,"languageCount":23,"license":"Apache-2.0","task":"Text Generation"} },
  { id: "sarvam-105b", type: "model", slug: "sarvam-105b", name: "Sarvam-105B", developer: "Sarvam AI", summary: "Large Sarvam model with a first-party model card and downloadable artifacts; publisher benchmarks remain labeled as publisher-reported.", summaryKind: "source-derived", sourceUrl: "https://huggingface.co/sarvamai/sarvam-105b", sourceLabel: "Official model card", categories: ["model", "indic", "local"], indiaRelevance: "Indian / Indic model ecosystem", local: true, verification: "verified", evidenceIds: ["ev-sarvam-105b"], facts: {"architecture":"MLA-style attention with MoE","context":"128K","developer":"Sarvam AI","indiaFocus":true,"languageCount":23,"license":"Apache-2.0","task":"Text Generation"} },
  { id: "openhathi-7b", type: "model", slug: "openhathi-7b", name: "OpenHathi-7B-Hi-v0.1-Base", developer: "Sarvam AI", summary: "Base model focused on Hindi, English and Hinglish; the source explicitly notes it is a base model rather than a ready-made chat assistant.", summaryKind: "source-derived", sourceUrl: "https://huggingface.co/sarvamai/OpenHathi-7B-Hi-v0.1-Base", sourceLabel: "Official model card", categories: ["model", "indic", "hindi", "local"], indiaRelevance: "Indian / Indic model ecosystem", local: true, verification: "verified", evidenceIds: ["ev-openhathi-7b"], facts: {"baseModel":true,"developer":"Sarvam AI","languages":["Hindi","English","Hinglish"],"license":"Llama 2","localArtifacts":["Safetensors","GGUF"],"parameters":"7B"} },
  { id: "airavata", type: "model", slug: "airavata", name: "Airavata", developer: "AI4Bharat", summary: "Hindi instruction-tuned model built from OpenHathi and the IndicInstruct dataset.", summaryKind: "source-derived", sourceUrl: "https://huggingface.co/ai4bharat/Airavata", sourceLabel: "Official model card", categories: ["model", "indic", "hindi", "local"], indiaRelevance: "Indian / Indic model ecosystem", local: true, verification: "verified", evidenceIds: ["ev-airavata"], facts: {"base":"OpenHathi","developer":"AI4Bharat","languages":["English","Hindi"],"license":"Llama 2","parameters":"7B","tuning":"IndicInstruct instruction tuning"} },
  { id: "krutrim-2-instruct", type: "model", slug: "krutrim-2-instruct", name: "Krutrim-2-Instruct", developer: "OLA Krutrim", summary: "Instruction-tuned 12B model built on Mistral-NeMo architecture with an India/Indic focus.", summaryKind: "source-derived", sourceUrl: "https://huggingface.co/krutrim-ai-labs/Krutrim-2-instruct", sourceLabel: "Official model card", categories: ["model", "indic", "local"], indiaRelevance: "Indian / Indic model ecosystem", local: true, verification: "verified", evidenceIds: ["ev-krutrim-2-instruct"], facts: {"architecture":"Mistral-NeMo 12B","context":"128K","developer":"OLA Krutrim Team","instructionTuned":true,"languageCount":13,"license":"Krutrim Community License Agreement v1.0","parameters":"12B"} },
  { id: "sarvam-ai", type: "provider", slug: "sarvam-ai", name: "Sarvam AI", developer: "Sarvam AI", summary: "India-focused AI company and model provider. This profile links only to first-party sources; unsupported compliance or market claims are not inferred.", summaryKind: "editorial", sourceUrl: "https://www.sarvam.ai/", sourceLabel: "First-party website", categories: ["provider"], indiaRelevance: "Indian AI provider", verification: "source-linked", evidenceIds: [] },
  { id: "ai4bharat", type: "provider", slug: "ai4bharat", name: "AI4Bharat", developer: "AI4Bharat", summary: "Indian-language AI research group. Detailed institutional claims remain source-linked unless separately verified.", summaryKind: "editorial", sourceUrl: "https://ai4bharat.org/", sourceLabel: "First-party website", categories: ["provider"], indiaRelevance: "Indian AI research", verification: "source-linked", evidenceIds: [] },
  { id: "krutrim", type: "provider", slug: "krutrim", name: "Krutrim AI Labs", developer: "Krutrim", summary: "Indian AI model provider. License and model facts belong on evidence-backed model records, not marketing badges.", summaryKind: "editorial", sourceUrl: "https://olakrutrim.com/", sourceLabel: "First-party website", categories: ["provider"], indiaRelevance: "Indian AI provider", verification: "source-linked", evidenceIds: [] },
];

